// <auto-generated />
using System;
using Infrastructure.AppDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(MainDataContext))]
    [Migration("20260817211001_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Admision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CitaMedicaId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CopagoOCuotaModeradora")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EPS")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaAdmision")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NumeroAutorizacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RegistradoPorUsuarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("TipoContrato")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("ValorConsulta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorNeto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CitaMedicaId")
                        .IsUnique();

                    b.HasIndex("PacienteId");

                    b.ToTable("Admisiones");
                });

            modelBuilder.Entity("Domain.Entities.CitaMedica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MotivoConsulta")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProfesionalId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.HasIndex("ProfesionalId");

                    b.ToTable("Citas");
                });

            modelBuilder.Entity("Domain.Entities.DiagnosticoConsulta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoCIE11")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("boolean");

                    b.Property<Guid>("HistoriaClinicaId")
                        .HasColumnType("uuid");

                    b.Property<string>("TipoDiagnostico")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("HistoriaClinicaId");

                    b.ToTable("DiagnosticosConsulta");
                });

            modelBuilder.Entity("Domain.Entities.DisponibilidadAgenda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("DuracionMinutosCita")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("interval");

                    b.Property<Guid>("ProfesionalId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProfesionalId");

                    b.ToTable("Disponibilidades");
                });

            modelBuilder.Entity("Domain.Entities.FacturaSalud", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdmisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("CUFE")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ValorBruto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorCopago")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorDescuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorNeto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AdmisionId")
                        .IsUnique();

                    b.HasIndex("PacienteId");

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("Domain.Entities.HistoriaClinica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AntecedentesFamiliares")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AntecedentesPersonales")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CitaMedicaId")
                        .HasColumnType("uuid");

                    b.Property<string>("EnfermedadActual")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EsInmutable")
                        .HasColumnType("boolean");

                    b.Property<string>("ExamenFisico")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MotivoConsulta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProfesionalId")
                        .HasColumnType("uuid");

                    b.Property<string>("RevisionPorSistemas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CitaMedicaId")
                        .IsUnique();

                    b.HasIndex("PacienteId");

                    b.HasIndex("ProfesionalId");

                    b.ToTable("HistoriasClinicas");
                });

            modelBuilder.Entity("Domain.Entities.NotaAclaratoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HistoriaClinicaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProfesionalId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("HistoriaClinicaId");

                    b.HasIndex("ProfesionalId");

                    b.ToTable("NotasAclaratorias");
                });

            modelBuilder.Entity("Domain.Entities.Paciente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EPS")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("RegimenSalud")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("TipoDocumento", "NumeroDocumento")
                        .IsUnique();

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("Domain.Entities.ProcedimientoConsulta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<string>("CodigoCUPS")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("HistoriaClinicaId")
                        .HasColumnType("uuid");

                    b.Property<string>("NombreProcedimiento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HistoriaClinicaId");

                    b.ToTable("ProcedimientosConsulta");
                });

            modelBuilder.Entity("Domain.Entities.ProfesionalSalud", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("NumeroRethus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("NumeroRethus")
                        .IsUnique();

                    b.ToTable("Profesionales");
                });

            modelBuilder.Entity("Domain.Entities.RipsTransaccion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CUV")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstadoValidacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("FacturaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JsonRips")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("FacturaId")
                        .IsUnique();

                    b.ToTable("RipsTransacciones");
                });

            modelBuilder.Entity("Domain.Entities.Admision", b =>
                {
                    b.HasOne("Domain.Entities.CitaMedica", "CitaMedica")
                        .WithOne()
                        .HasForeignKey("Domain.Entities.Admision", "CitaMedicaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CitaMedica");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Domain.Entities.CitaMedica", b =>
                {
                    b.HasOne("Domain.Entities.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.ProfesionalSalud", "Profesional")
                        .WithMany()
                        .HasForeignKey("ProfesionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Paciente");

                    b.Navigation("Profesional");
                });

            modelBuilder.Entity("Domain.Entities.DiagnosticoConsulta", b =>
                {
                    b.HasOne("Domain.Entities.HistoriaClinica", null)
                        .WithMany("Diagnosticos")
                        .HasForeignKey("HistoriaClinicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.DisponibilidadAgenda", b =>
                {
                    b.HasOne("Domain.Entities.ProfesionalSalud", "Profesional")
                        .WithMany()
                        .HasForeignKey("ProfesionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Profesional");
                });

            modelBuilder.Entity("Domain.Entities.FacturaSalud", b =>
                {
                    b.HasOne("Domain.Entities.Admision", "Admision")
                        .WithOne()
                        .HasForeignKey("Domain.Entities.FacturaSalud", "AdmisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admision");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Domain.Entities.HistoriaClinica", b =>
                {
                    b.HasOne("Domain.Entities.CitaMedica", "CitaMedica")
                        .WithOne()
                        .HasForeignKey("Domain.Entities.HistoriaClinica", "CitaMedicaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.ProfesionalSalud", "Profesional")
                        .WithMany()
                        .HasForeignKey("ProfesionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CitaMedica");

                    b.Navigation("Paciente");

                    b.Navigation("Profesional");
                });

            modelBuilder.Entity("Domain.Entities.NotaAclaratoria", b =>
                {
                    b.HasOne("Domain.Entities.HistoriaClinica", null)
                        .WithMany("NotasAclaratorias")
                        .HasForeignKey("HistoriaClinicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.ProfesionalSalud", "Profesional")
                        .WithMany()
                        .HasForeignKey("ProfesionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Profesional");
                });

            modelBuilder.Entity("Domain.Entities.ProcedimientoConsulta", b =>
                {
                    b.HasOne("Domain.Entities.HistoriaClinica", null)
                        .WithMany("Procedimientos")
                        .HasForeignKey("HistoriaClinicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.RipsTransaccion", b =>
                {
                    b.HasOne("Domain.Entities.FacturaSalud", "Factura")
                        .WithOne()
                        .HasForeignKey("Domain.Entities.RipsTransaccion", "FacturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("Domain.Entities.HistoriaClinica", b =>
                {
                    b.Navigation("Diagnosticos");

                    b.Navigation("NotasAclaratorias");

                    b.Navigation("Procedimientos");
                });
#pragma warning restore 612, 618
        }
    }
}
